### ISSUE TITLE
boot2docker build

### ISSUE THREAD

**Issue by michfuer** [advancingu/SfDocker#1]
Thanks for your efforts on this!

I'm running docker on my Mac with boot2docker. If I try

```
docker-compose up
```

I get 

```
compose.progress_stream.StreamOutputError: Error: image symfony/app-code-dynamic:latest not found
```

Should I be running 'build.sh' in the docker VM? I feel like I'm missing some installation steps...

**Comment by hacfi** [comment]
@michfuer Run https://github.com/advancingu/SfDocker/blob/master/build.sh#L81-85
The script itself is for Ubuntu so try if just building the images works out of the box.

**Comment by michfuer** [comment]
So it looks like the boot2docker VM doesn't come with the 'apt-get' utility. So is the idea that you'll have two options for building your containers 1) 'docker-compose up' and 2) execute build.sh? I noticed in the build.sh that it's doing a 'docker build' on each image, but I thought that's what docker-compose is for.

I verified I can get the images to build manually.

**Comment by hacfi** [comment]
@michfuer `apt-get` is the ubuntu/debian package manager. `build.sh` is for Ubuntu users to set up their local machine to have all the necessary packages (mysql, php, curl, phpunit etc) installed. If the images built everything should be fine.

**Comment by michfuer** [comment]
@hacfi yeah, so boot2docker is the recommended method for getting docker running on mac OS X, https://docs.docker.com/installation/mac/ but this quote "The Boot2Docker management tool is a lightweight Linux virtual machine made specifically to run the Docker daemon on Mac OS X." means the boot2docker VM isn't compatible with the build.sh.

So I'm thinking my options are 1) Get a plain vanilla VM of Ubuntu 14.04 and run the build.sh on that, or 2) figure out why 'docker-compose up' isn't working. Does 'docker-compose up' work for you?

**Comment by hacfi** [comment]
We shouldn’t depend on starting a Ubuntu VM. We can add a .sh for OS X which uses brew to install the dependencies.

build.sh is just a helper..you don’t need it necessarily.

**Comment by advancingu** [comment]
As @hacfi wrote (thanks), `build.sh` is simply a helper script to set up a development environment under Ubuntu.

I've just added instructions on how to manually build the Docker images in 73999ac47d2aac31508ee. Please reopen if building like this doesn't work for you.

**Comment by michfuer** [comment]
@hacfi @advancingu Thanks for the info. I'm more interested in the docker-compose.yml file working on my Mac as opposed to building each image individually. If I remove the "symfony/" prefix from the image paths I can get most of the images to build but the php-dev image broke for me here

```
RUN apt-get install -y php5-xdebug
```

Changing to 

```
RUN apt-get update && apt-get install -y php5-xdebug
```

seemed to fix it. I was gonna put in a pull request, but got sidetracked and haven't got it just right yet :)

**Comment by advancingu** [comment]
Just for your information, building the `php-dev` image will fail like this if there was a change to PHP packages in Ubuntu (e.g. a security update) after you had already built the parent image `php`. Running `apt-get update` will allow you to install the xdebug package but this will mean that the `php` and `php-dev` images will then have been built with two different PHP versions. If you only do development, this won't have any impact for you however.

I don't see why removing `symfony/` would make the build fail. What error are you getting?
